version: '3'
services:
    react-app:
        image: react-app-production:production
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - caddy-data:/data
            - caddy-config:/config
        networks:
            - buyit-app
    api-server:
        image: api-server
        restart: unless-stopped
        ports:
            - '5000:5000'
        networks:
            - buyit-app
networks:
    buyit-app:
        driver: bridge
volumes:
    caddy-data:
        driver: local
    caddy-config:
        driver: local
